name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test
